# Generated by Django 2.0.7 on 2018-07-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(choices=[('Informatica', '<i class="fas fa-laptop"></i>'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Senior', max_length=2)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('text', models.TextField(verbose_name='Detalhes')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nome da Entidade')),
                ('image', models.ImageField(blank=True, upload_to='Media/Images', verbose_name='Imagem')),
                ('pub_data', models.DateTimeField(verbose_name='Publicado')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprego.Categoria')),
            ],
            options={
                'verbose_name': 'emprego',
                'verbose_name_plural': 'empregos',
                'ordering': ('pub_data',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('code', models.CharField(max_length=5, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.AddField(
            model_name='emprego',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endereco', to='emprego.Endereco'),
        ),
    ]
