# Generated by Django 2.0.7 on 2018-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icon',
            field=models.CharField(choices=[('<i class="fas fa-laptop"></i>', 'Informatica'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Senior', max_length=2),
        ),
    ]
